apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operatorhubio-dev
commonLabels:
  app: operatorhubio
bases:
  - ../base
resources:
  - route.yaml
images:
  - name: site
    newName: quay.io/operator-framework/operatorhubio
    newTag: dev
  - name: catalog
    newName: quay.io/operator-framework/operatorhubio
    newTag: catalog
