apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  creationTimestamp: 2020-03-31T12:24:02Z
  name: operatorhubio
spec:
  host: dev.operatorhub.io
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: operatorhubio
    weight: 100
  wildcardPolicy: None
