apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operatorhubio-prod
commonLabels:
  app: operatorhubio
bases:
  - ../base
resources:
  - route.yaml
patchesStrategicMerge:
  - patch-deploy-replicas.yaml
images:
  - name: site
    newName: quay.io/operator-framework/operatorhubio
    newTag: v3
  - name: catalog
    newName: quay.io/operator-framework/operatorhubio
    newTag: catalog-buster
